http:
  hostname: ""
  port: 8080
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  shutdownTimeout: "10s"
  tls:
    enabled: false
    certificate: ""
    key: ""

app:
  name: "Bandeira"
  host: "http://localhost:8080"
  environment: "local"
  encryptionKey: "?E(G+KbPeShVmYq3t6w9z$C&F)J@McQf"
  timeout: "20s"

cache:
  capacity: 100000
  expiration:
    staticFile: "4380h"

database:
  driver: "sqlite3"
  connection: "dbs/main.db?_journal=WAL&_timeout=5000&_fk=true"
  testConnection: "file:/$RAND?vfs=memdb&_timeout=1000&_fk=true"

auth:
  adminPassword: "change-me-in-production"
